language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t my-python-app -f ./demos/simpleapp .

after_success:
  - docker images
