language: python
python:
  - "3.8"

env:
  global:
    - GlobalVar1=false
    - GlobalVar2=true

before_install:
  - pip install flake8 bandit

before_script:
  - flake8 main.py
  - bandit -r .

install:
  - pip install -r ./demos/ml-app/requirements.txt

script:
  - cd ./demos/ml-app
  - python -m unittest discover ./demos/ml-app/tests

jobs:
  include:
    - stage: Lint and Security Checks
      script:
        - echo "Running lint and security checks..."
        - cd ./demos/ml-app
        - flake8 main.py
        - bandit -r .

    - stage: Install Dependencies and Test
      script:
        - echo "Installing dependencies and running tests..."
        - cd ./demos/ml-app
        - pip install -r requirements.txt
        - python -m unittest discover tests
