services:
  - docker

env:
  global:
    - GlobalVar1=false
    - GlobalVar2=true



before_script:
  - cd ./demos/ml-app



jobs:
  include:
    - stage: Lint and Security Checks
      script:
      # Run docker build with TRAVISCI build id as tag for docker image:  registry/user/image
      - docker build -t my-python-app:$TRAVIS_BUILD_NUMBER .
      
