
services:
  - docker

env:
  global:
    - GlobalVar1=false
    - GlobalVar2=true

before_script:
  - cd ./demos/ml-app

jobs:
# Rund docker build only strategy:
  include:
    - stage: Build Docker Image
      script:
        - echo "Building Docker Image..."
        - pwd
        - echo "force step to exit if there are any errors"
        - set -e
        - docker build -t my-python-app -f .
        - docker images
        # View reportes from the container under folder /reports
        - docker run my-python-app cat /reports
        # Use build number as tag
        - docker tag my-python-app yanivomc/my-python-app:$TRAVIS_BUILD_NUMBER
        # push the image to docker hub
        - docker push yanivomc/my-python-app:$TRAVIS_BUILD_NUMBER
